import "./style/banner.scss";
import "destyle.css/destyle.css";
// import 'selectize/dist/css/selectize.css';
import "./style/blocks/wpcf7.scss";
import "./style/blocks/btn.scss";
import "./style/blocks/checkbox.scss";
import "./style/blocks/input.scss";
import "./style/blocks/select.scss";
import "./style/fonts.scss";
import "./style/common.scss";
import "./style/typography.scss";

// import './modules/photoswipe/photoswipe.scss';
// import './modules/photoswipe/default-skin.scss';

import './modules/popup/popup.scss';
import './modules/header/header.scss';
import './modules/top/top.scss';
import './modules/discount/discount.scss';
import './modules/catalog/catalog.scss';
import './modules/quiz/quiz.scss';
import './modules/quality/quality.scss';
import './modules/advantages/advantages.scss';
import './modules/prices/prices.scss';
import './modules/testimonials/testimonials.scss';
import './modules/order/order.scss';
import './modules/process/process.scss';
import './modules/faq/faq.scss';
import './modules/footer/footer.scss';
import './modules/form/form.scss';
